import LearningSession from '../models/LearningSession.js';
import { 
  generateMentorResponse, 
  analyzeProjectSummary, 
  evaluateDefenseAnswer,
  compileCareerCoachRoadmap
} from '../services/learningLabAiService.js';
import { executeJsCode } from '../services/codeExecutionService.js';
import axios from 'axios';

// Ignore media, node_modules, build/dist, and lock files to prevent context overload
const IGNORE_PATTERNS = [
  /node_modules/i,
  /dist/i,
  /build/i,
  /coverage/i,
  /\.git/i,
  /\.cache/i,
  /package-lock\.json/i,
  /yarn\.lock/i,
  /pnpm-lock\.yaml/i,
  /\.(png|jpe?g|gif|svg|woff2?|eot|ttf|mp3|mp4|webm|zip|tar\.gz|ico|map)$/i
];

const isIgnored = (path) => {
  return IGNORE_PATTERNS.some(pattern => pattern.test(path));
};

// Fetch repository contents recursively from GitHub REST API with safe limit
const fetchGitHubRepoContents = async (owner, repo, path = '', filesCollected = [], depth = 0) => {
  if (depth > 4 || filesCollected.length > 35) return filesCollected; // Limit traversal to avoid rate limit or memory overflows
  
  try {
    const url = `https://api.github.com/repos/${owner}/${repo}/contents/${path}`;
    const headers = {};
    if (process.env.GITHUB_TOKEN) {
      headers.Authorization = `token ${process.env.GITHUB_TOKEN}`;
    }
    
    const response = await axios.get(url, { headers, timeout: 8000 });
    
    if (Array.isArray(response.data)) {
      for (const item of response.data) {
        if (isIgnored(item.path)) continue;
        
        if (item.type === 'dir') {
          await fetchGitHubRepoContents(owner, repo, item.path, filesCollected, depth + 1);
        } else if (item.type === 'file' && item.size < 120000) { // Limit size to 120KB
          filesCollected.push({
            path: item.path,
            downloadUrl: item.download_url,
            size: item.size
          });
        }
      }
    }
  } catch (error) {
    console.error(`GitHub fetch error for path ${path}:`, error.message);
  }
  return filesCollected;
};

/**
 * GET user sessions
 */
export const getLearningSessions = async (req, res) => {
  try {
    const sessions = await LearningSession.find({ userId: req.user._id })
      .sort({ updatedAt: -1 })
      .select('topic mode masteryPercentage updatedAt status');
      
    return res.status(200).json({ success: true, data: sessions });
  } catch (error) {
    return res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * GET specific session
 */
export const getLearningSession = async (req, res) => {
  try {
    const session = await LearningSession.findOne({ _id: req.params.id, userId: req.user._id });
    if (!session) {
      return res.status(404).json({ success: false, message: 'Learning session not found.' });
    }
    return res.status(200).json({ success: true, data: session });
  } catch (error) {
    return res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * POST create learning session
 */
export const createLearningSession = async (req, res) => {
  const { topic, mode = 'Intermediate', personality = 'The Coding Coach', sessionType = 'Concept Learning' } = req.body;
  if (!topic) {
    return res.status(400).json({ success: false, message: 'A topic is required.' });
  }

  try {
    const session = new LearningSession({
      userId: req.user._id,
      topic,
      mode,
      personality,
      sessionType,
      messages: []
    });

    // Auto-initialize first AI explanation to welcome user
    const aiResponse = await generateMentorResponse({
      topic,
      mode,
      messages: [{ role: 'user', text: `Hi, please teach me about ${topic}.` }],
      personality,
      sessionType
    });

    session.messages.push({
      id: `init-${Date.now()}`,
      role: 'assistant',
      text: aiResponse.text,
      playgroundChallenge: aiResponse.playgroundChallenge,
      structuredContent: aiResponse.structuredContent,
      timestamp: new Date()
    });

    // Save checklist tasks and suggestions generated by AI
    if (aiResponse.missionChecklistUpdates) {
      session.missionChecklist = aiResponse.missionChecklistUpdates.map(u => ({
        task: u.task,
        completed: !!u.completed
      }));
    } else {
      session.missionChecklist = [
        { task: `Understand basic concepts of ${topic}`, completed: true },
        { task: `Practice ${topic} in safe sandbox playground`, completed: false },
        { task: `Solve AI challenge to achieve mastery`, completed: false }
      ];
    }

    if (aiResponse.suggestedNextStep) {
      session.suggestedNextStep = aiResponse.suggestedNextStep;
    } else {
      session.suggestedNextStep = {
        title: `Explore ${topic} theory`,
        actionText: `Read through the AI mentor's initial explanation to understand structural definitions.`,
        targetTab: `notes`
      };
    }

    session.masteryPercentage = aiResponse.masteryDelta || 5;
    await session.save();

    return res.status(201).json({ success: true, data: session });
  } catch (error) {
    console.error('Create learning session failed:', error.message);
    return res.status(500).json({ success: false, message: 'Failed to start learning session.' });
  }
};

/**
 * POST send message in chat
 */
export const sendChatMessage = async (req, res) => {
  const { text } = req.body;
  if (!text) {
    return res.status(400).json({ success: false, message: 'Message text is required.' });
  }

  try {
    const session = await LearningSession.findOne({ _id: req.params.id, userId: req.user._id });
    if (!session) {
      return res.status(404).json({ success: false, message: 'Learning session not found.' });
    }

    // Append user message
    session.messages.push({
      id: `u-${Date.now()}`,
      role: 'user',
      text,
      timestamp: new Date()
    });

    // Generate AI response
    const aiResponse = await generateMentorResponse({
      topic: session.topic,
      mode: session.mode,
      messages: session.messages,
      personality: session.personality,
      sessionType: session.sessionType
    });

    session.messages.push({
      id: `a-${Date.now()}`,
      role: 'assistant',
      text: aiResponse.text,
      playgroundChallenge: aiResponse.playgroundChallenge,
      structuredContent: aiResponse.structuredContent,
      timestamp: new Date()
    });

    // Update suggested next actions & checklist objectives
    if (aiResponse.suggestedNextStep) {
      session.suggestedNextStep = aiResponse.suggestedNextStep;
    }
    
    if (aiResponse.missionChecklistUpdates) {
      aiResponse.missionChecklistUpdates.forEach(update => {
        const existing = session.missionChecklist.find(item => item.task.toLowerCase() === update.task.toLowerCase());
        if (existing) {
          existing.completed = !!update.completed;
        } else {
          session.missionChecklist.push({ task: update.task, completed: !!update.completed });
        }
      });
    }

    // Update mastery progress
    session.masteryPercentage = Math.min(100, session.masteryPercentage + (aiResponse.masteryDelta || 5));
    await session.save();

    return res.status(200).json({ success: true, data: session });
  } catch (error) {
    console.error('Send chat message failed:', error.message);
    return res.status(500).json({ success: false, message: 'Failed to process chat message.' });
  }
};

/**
 * POST run code in sandbox
 */
export const runSandboxCode = async (req, res) => {
  const { code } = req.body;
  if (!code) {
    return res.status(400).json({ success: false, message: 'Code is required.' });
  }

  try {
    const result = await executeJsCode(code);
    return res.status(200).json({ success: true, data: result });
  } catch (error) {
    return res.status(500).json({ success: false, message: error.message });
  }
};

/**
 * POST submit code for evaluation
 */
export const submitSandboxCode = async (req, res) => {
  const { code, challengeTitle } = req.body;
  if (!code) {
    return res.status(400).json({ success: false, message: 'Code is required.' });
  }

  try {
    const session = await LearningSession.findOne({ _id: req.params.id, userId: req.user._id });
    if (!session) {
      return res.status(404).json({ success: false, message: 'Learning session not found.' });
    }

    // Exec sandbox
    const runResult = await executeJsCode(code);

    // Call AI to review code structure, validation logic
    const reviewPrompt = `
Review this sandbox code submission for the challenge "${challengeTitle || session.topic}".
Code Submitted:
\`\`\`javascript
${code}
\`\`\`
Stdout output from secure console:
"${runResult.stdout}"
Sandbox error (if any): "${runResult.error || 'None'}"

Output strict JSON:
{
  "passed": true | false,
  "feedback": "constructive 1-2 sentence developer code review, highlighting efficiency, styling, or logic bugs."
}
`;

    // Make AI call using standard mentor response loop
    const aiResponse = await generateMentorResponse({
      topic: `Code Review: ${challengeTitle || session.topic}`,
      mode: session.mode,
      messages: [{ role: 'user', text: reviewPrompt }]
    });

    const parsedReview = typeof aiResponse.text === 'string' ? JSON.parse(aiResponse.text.trim()) : aiResponse;

    // Append submission evaluation logs to the last message containing the challenge
    const lastMsgIdx = session.messages.slice().reverse().findIndex(m => m.playgroundChallenge && m.playgroundChallenge.title);
    if (lastMsgIdx !== -1) {
      const idx = session.messages.length - 1 - lastMsgIdx;
      session.messages[idx].playgroundChallenge.userSubmission = code;
      session.messages[idx].playgroundChallenge.stdout = runResult.stdout;
      session.messages[idx].playgroundChallenge.evaluation = {
        passed: parsedReview.passed,
        feedback: parsedReview.feedback
      };
      if (parsedReview.passed) {
        session.masteryPercentage = Math.min(100, session.masteryPercentage + 15);
      }
      session.markModified('messages');
      await session.save();
    }

    return res.status(200).json({
      success: true,
      data: {
        passed: parsedReview.passed,
        feedback: parsedReview.feedback,
        stdout: runResult.stdout,
        error: runResult.error,
        masteryPercentage: session.masteryPercentage
      }
    });
  } catch (error) {
    console.error('Submit code failed:', error.message);
    return res.status(500).json({ success: false, message: 'Failed to evaluate code submission.' });
  }
};

/**
 * POST ingest project folder or github repo url
 */
export const ingestProject = async (req, res) => {
  const { githubUrl, files = [], projectName = 'Project Defense' } = req.body;
  
  try {
    let projectSummaryText = '';
    let filesList = [];

    // PROJECT SUMMARIZER LAYER & CONTEXT COMPRESSION
    if (githubUrl) {
      const parts = githubUrl.replace('https://github.com/', '').split('/');
      if (parts.length < 2) {
        return res.status(400).json({ success: false, message: 'Invalid GitHub URL.' });
      }
      const owner = parts[0];
      const repo = parts[1].replace('.git', '');
      
      filesList = await fetchGitHubRepoContents(owner, repo);
      
      // Pull package.json and config contents to compress context
      const packageJsonFile = filesList.find(f => f.path.endsWith('package.json'));
      let packageJsonContent = '';
      if (packageJsonFile && packageJsonFile.downloadUrl) {
        try {
          const resPkg = await axios.get(packageJsonFile.downloadUrl);
          packageJsonContent = JSON.stringify(resPkg.data, null, 2);
        } catch (e) {}
      }

      projectSummaryText = `
Ingested GitHub Repository: ${githubUrl}
List of Scanned Files (Ignored node_modules, lock files, binary elements):
${filesList.map(f => `- ${f.path} (${f.size} bytes)`).join('\n')}

package.json:
${packageJsonContent || 'Not found'}
`;
    } else if (Array.isArray(files) && files.length > 0) {
      // Ingestion of individual uploaded files
      const filtered = files.filter(f => !isIgnored(f.path)).slice(0, 30);
      const packageFile = filtered.find(f => f.path.endsWith('package.json'));
      
      projectSummaryText = `
Ingested Uploaded Folder files:
${filtered.map(f => `- ${f.path} (${f.content ? f.content.length : 0} chars)`).join('\n')}

package.json Content:
${packageFile ? packageFile.content : 'Not found'}
`;
    } else {
      return res.status(400).json({ success: false, message: 'Please provide a GitHub URL or uploaded files.' });
    }

    // Call AI Ingestor to generate Architecture summary and Top 25 Questions
    const analysisReport = await analyzeProjectSummary({
      projectSummaryText,
      repoUrl: githubUrl || ''
    });

    const session = new LearningSession({
      userId: req.user._id,
      topic: `Project Defense: ${projectName}`,
      mode: 'Advanced',
      status: 'active',
      projectContext: {
        projectName,
        repoUrl: githubUrl || '',
        architectureReport: analysisReport.architectureReport,
        defenseProgress: {
          currentQuestionIndex: 0,
          totalQuestions: 5,
          evaluations: []
        },
        topQuestions: analysisReport.topQuestions,
        learningReport: {
          strengths: [],
          weakAreas: [],
          missingConcepts: [],
          suggestedImprovements: [],
          refactoringIdeas: [],
          productionReadinessScore: 0,
          portfolioReadinessScore: 0
        }
      }
    });

    // Start with the starter defense question issued by the AI
    session.messages.push({
      id: `defense-init-${Date.now()}`,
      role: 'assistant',
      text: `### 🎯 Project Defense Commenced!\nI have completed parsing your repository codebase and compiled the full **Architecture Understanding Report**.\n\nHere is your first Project Defense question based on your setup:\n\n**"${analysisReport.starterDefenseQuestion}"**`,
      timestamp: new Date()
    });

    await session.save();
    return res.status(201).json({ success: true, data: session });
  } catch (error) {
    console.error('Project ingestion failed:', error.message);
    return res.status(500).json({ success: false, message: 'Failed to analyze project codebase.' });
  }
};

/**
 * POST submit response to project defense question
 */
export const submitProjectDefenseAnswer = async (req, res) => {
  const { answer } = req.body;
  if (!answer) {
    return res.status(400).json({ success: false, message: 'Answer is required.' });
  }

  try {
    const session = await LearningSession.findOne({ _id: req.params.id, userId: req.user._id });
    if (!session) {
      return res.status(404).json({ success: false, message: 'Learning session not found.' });
    }

    const context = session.projectContext;
    if (!context || !context.architectureReport) {
      return res.status(400).json({ success: false, message: 'This learning session is not a project defense session.' });
    }

    const progress = context.defenseProgress;
    const currentQIdx = progress.currentQuestionIndex;
    
    // Extract current question text from last message
    const lastMsg = session.messages[session.messages.length - 1];
    let currentQuestion = lastMsg.text;
    if (currentQuestion.includes('**"')) {
      currentQuestion = currentQuestion.split('**"')[1].split('"**')[0];
    }

    // Evaluate answer with AI
    const evalResult = await evaluateDefenseAnswer({
      report: context.architectureReport,
      currentQuestion,
      answer,
      currentQuestionIndex: currentQIdx
    });

    // Append evaluation details
    progress.evaluations.push({
      question: currentQuestion,
      answer,
      authorshipScore: evalResult.authorshipScore,
      feedback: evalResult.feedback
    });

    // Append user response to chat logs
    session.messages.push({
      id: `u-def-${Date.now()}`,
      role: 'user',
      text: answer,
      timestamp: new Date()
    });

    if (evalResult.isCompleted) {
      // Completed! Generate final learning scores and report
      session.status = 'completed';
      context.learningReport = evalResult.learningReport;
      
      // Calculate overall mastery
      session.masteryPercentage = evalResult.learningReport.productionReadinessScore;

      session.messages.push({
        id: `a-def-summary-${Date.now()}`,
        role: 'assistant',
        text: `### 🏁 Project Defense Completed!\n\n**Authorship Check Summary**:\n${evalResult.feedback}\n\nWe have finalized your comprehensive **Project Readiness Report** inside the learning dashboard tab containing refactoring roadmaps and portfolio readiness grades. Great job defending your implementation choices!`,
        timestamp: new Date()
      });
    } else {
      // Prompt next question
      progress.currentQuestionIndex += 1;
      
      session.messages.push({
        id: `a-def-next-${Date.now()}`,
        role: 'assistant',
        text: `**Feedback**: ${evalResult.feedback}\n\nHere is your next Project Defense question:\n\n**"${evalResult.nextQuestion}"**`,
        timestamp: new Date()
      });
    }

    session.markModified('projectContext');
    session.markModified('messages');
    await session.save();

    return res.status(200).json({ success: true, data: session });
  } catch (error) {
    console.error('Submit project defense failed:', error.message);
    return res.status(500).json({ success: false, message: 'Failed to process project defense response.' });
  }
};

/**
 * POST compile career coach roadmap
 */
export const getCareerCoachRoadmap = async (req, res) => {
  const { topic = 'Full Stack Development' } = req.body;

  try {
    // Collect candidate skills memory
    const completedSessions = await LearningSession.find({ userId: req.user._id, status: 'completed' });
    const weakSkills = [];
    const masteredSkills = [];

    // Analyze previous learning states
    completedSessions.forEach(s => {
      if (s.masteryPercentage >= 75) {
        masteredSkills.push(s.topic);
      } else if (s.masteryPercentage < 50) {
        weakSkills.push(s.topic);
      }
    });

    const coachData = await compileCareerCoachRoadmap({
      masteredSkills,
      weakSkills,
      topic
    });

    return res.status(200).json({ success: true, data: coachData });
  } catch (error) {
    console.error('Career Coach generation failed:', error.message);
    return res.status(500).json({ success: false, message: 'Failed to process Career Coach roadmap.' });
  }
};

/**
 * PUT update learning session details (personality, mode, checklists)
 */
export const updateLearningSession = async (req, res) => {
  const { mode, personality, sessionType, status, missionChecklist } = req.body;
  try {
    const session = await LearningSession.findOne({ _id: req.params.id, userId: req.user._id });
    if (!session) {
      return res.status(404).json({ success: false, message: 'Learning session not found.' });
    }
    
    if (mode) session.mode = mode;
    if (personality) session.personality = personality;
    if (sessionType) session.sessionType = sessionType;
    if (status) session.status = status;
    if (Array.isArray(missionChecklist)) {
      session.missionChecklist = missionChecklist;
    }
    
    await session.save();
    return res.status(200).json({ success: true, data: session });
  } catch (error) {
    return res.status(500).json({ success: false, message: error.message });
  }
};
